# Generated by Codex on 2026-03-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("dj_wallet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="hash_algo",
            field=models.CharField(default="sha256", max_length=32),
        ),
        migrations.AddField(
            model_name="transaction",
            name="prev_tx_hash",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="transaction",
            name="tx_hash",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.CreateModel(
            name="WalletRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "max_withdraw_amount",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=64, null=True
                    ),
                ),
                (
                    "max_transfer_amount",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=64, null=True
                    ),
                ),
                (
                    "min_balance_required",
                    models.DecimalField(decimal_places=8, default=0, max_digits=64),
                ),
                (
                    "daily_outflow_limit",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=64, null=True
                    ),
                ),
                (
                    "monthly_outflow_limit",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=64, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ComplianceProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("risk_score", models.PositiveSmallIntegerField(default=0)),
                ("is_suspended", models.BooleanField(default=False)),
                (
                    "daily_limit",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=64, null=True
                    ),
                ),
                (
                    "monthly_limit",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=64, null=True
                    ),
                ),
                ("flags", models.JSONField(blank=True, default=dict, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("holder_id", models.PositiveIntegerField()),
                (
                    "holder_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WalletRoleAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("holder_id", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "holder_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dj_wallet.walletrole",
                    ),
                ),
            ],
            options={
                "unique_together": {("holder_type", "holder_id", "role")},
            },
        ),
        migrations.CreateModel(
            name="TransactionSignature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scheme",
                    models.CharField(
                        choices=[
                            ("hmac-sha256", "HMAC-SHA256"),
                            ("ed25519", "Ed25519"),
                            ("secp256k1", "Secp256k1"),
                        ],
                        max_length=32,
                    ),
                ),
                ("public_key", models.TextField(blank=True, default="")),
                ("signature", models.TextField()),
                ("key_id", models.CharField(blank=True, default="", max_length=128)),
                ("signer_id", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "signer_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signatures",
                        to="dj_wallet.transaction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChainAnchor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chain", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("submitted", "Submitted"),
                            ("confirmed", "Confirmed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("onchain_tx_hash", models.CharField(blank=True, default="", max_length=256)),
                ("error", models.TextField(blank=True, default="")),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anchor",
                        to="dj_wallet.transaction",
                    ),
                ),
            ],
        ),
    ]
