# Generated by Codex on 2026-03-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("dj_wallet", "0003_user_signing"),
    ]

    operations = [
        migrations.CreateModel(
            name="CashAgent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=64, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "daily_limit",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=64, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("holder_id", models.PositiveIntegerField()),
                (
                    "holder_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CashRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=8, max_digits=64),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("cashin", "Cash In"), ("cashout", "Cash Out")],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("meta", models.JSONField(blank=True, default=dict, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("holder_id", models.PositiveIntegerField()),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="dj_wallet.cashagent",
                    ),
                ),
                (
                    "holder_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
    ]
