# Generated by Codex on 2026-03-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dj_wallet", "0004_cash_requests"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransferReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=64, unique=True)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "transfer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dj_wallet.transfer",
                    ),
                ),
            ],
        ),
    ]
