version: "3.9"

services:
  vwallet-web:
    build:
      context: .
      dockerfile: Dockerfile
    image: vwallet-web:local
    ports:
      - "8000:8000"
    environment:
      DJANGO_DEBUG: "1"
      DJANGO_ALLOWED_HOSTS: "*"
      DJ_WALLET_SIGNING_SECRET: "dev-signing-secret-change-me"
      DJ_WALLET_CHAIN_RPC_URL: "http://host.docker.internal:8545"
      DJ_WALLET_CHAIN_ID: "20260321"
      DJ_WALLET_ANCHOR_CONTRACT_ADDRESS: "0xC6d213e289d1F1aAe51E567DeaC4E5CE7e17ad23"
      DJ_WALLET_CHAIN_PRIVATE_KEY: "REPLACE_ME"
    volumes:
      - .:/app
