# Generated by Django 5.2.10 on 2026-01-17 16:10

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder_id', models.PositiveIntegerField()),
                ('slug', models.SlugField(default='default', help_text='The name of the wallet')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('balance', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=64)),
                ('decimal_places', models.PositiveSmallIntegerField(default=8)),
                ('meta', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('holder_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
                'db_table': 'wallet',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payable_id', models.PositiveIntegerField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('type', models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=64)),
                ('confirmed', models.BooleanField(default=True)),
                ('meta', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payable_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='contenttypes.contenttype')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='django_wallets.wallet')),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_id', models.PositiveIntegerField()),
                ('to_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('exchange', 'Exchange'), ('transfer', 'Transfer'), ('paid', 'Paid'), ('refund', 'Refund'), ('gift', 'Gift')], default='transfer', max_length=20)),
                ('discount', models.DecimalField(decimal_places=8, default=0, max_digits=64)),
                ('fee', models.DecimalField(decimal_places=8, default=0, max_digits=64)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_deposit', to='django_wallets.transaction')),
                ('from_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_sent', to='contenttypes.contenttype')),
                ('to_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_received', to='contenttypes.contenttype')),
                ('withdraw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_withdraw', to='django_wallets.transaction')),
            ],
            options={
                'db_table': 'transfer',
                'indexes': [models.Index(fields=['from_type', 'from_id'], name='transfer_from_ty_87c04c_idx'), models.Index(fields=['to_type', 'to_id'], name='transfer_to_type_eec14d_idx'), models.Index(fields=['status'], name='transfer_status_0f182e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['holder_type', 'holder_id', 'slug'], name='wallet_holder__8b1820_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together={('holder_type', 'holder_id', 'slug')},
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['payable_type', 'payable_id'], name='transaction_payable_77c518_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['type'], name='transaction_type_d14ecd_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['confirmed'], name='transaction_confirm_3d71bc_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['wallet', 'type'], name='transaction_wallet__11447a_idx'),
        ),
    ]
